---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: iambatman
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/findit_books
  jpa:
    properties:
      hibernate:
        dialet: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  application:
    name: Book-Detail-Service
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 8081

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
