---
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: "API-GATEWAY"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: GET-book-route
          uri: lb://Book-Detail-Service
          predicates:
            - Path=/api/books
            - Method=GET,POST
          filters:
            - StripPrefix=2
            - PrefixPath=/book-service

        - id: GET-user-route
          uri: lb://User-Detail-Service
          predicates:
            - Path=/api/users/{segment}
            - Method=GET
          filters:
            - StripPrefix=2
            - PrefixPath=/user-service

        - id: POST-user-route
          uri: lb://User-Detail-Service
          predicates:
            - Path=/api/users
            - Method=POST
          filters:
            - StripPrefix=2
            - PrefixPath=/user-service
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "gateway"
